// <auto-generated />
namespace ASP_MVC5_CRUD_Employees.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DataAnnotations_Validaciones_del_Modelo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DataAnnotations_Validaciones_del_Modelo));
        
        string IMigrationMetadata.Id
        {
            get { return "201712240435036_DataAnnotations_Validaciones_del_Modelo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
